// <auto-generated />
using System;
using ChurrOS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChurrOS.Api.Migrations
{
    [DbContext(typeof(ChurrosDbContext))]
    [Migration("20260522083851_RetypeCpuGpuMetricsAsGauge")]
    partial class RetypeCpuGpuMetricsAsGauge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChurrOS.Api.Domain.Account", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Domains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domains");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encryption_key");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Owners")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("owners");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Domains")
                        .HasDatabaseName("ix_account_domains");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Domains"), "GIN");

                    b.ToTable("account", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Acl", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_acl");

                    b.ToTable("acl", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.AclMember", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("AclId")
                        .HasColumnType("bigint")
                        .HasColumnName("acl_id");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<byte>("Permission")
                        .HasColumnType("smallint")
                        .HasColumnName("permission");

                    b.HasKey("AccountId", "AclId", "IdentityId")
                        .HasName("pk_acl_member");

                    b.HasIndex("AccountId", "IdentityId")
                        .HasDatabaseName("ix_acl_member_account_id_identity_id");

                    b.ToTable("acl_member", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApiKey", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_api_key");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_api_key_account_id_created_by_id");

                    b.HasIndex("AccountId", "IdentityId")
                        .HasDatabaseName("ix_api_key_account_id_identity_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_api_key_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_account_id_value");

                    b.ToTable("api_key", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Application", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AclId")
                        .HasColumnType("bigint")
                        .HasColumnName("acl_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<byte[]>("DeploymentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("deployment_hash");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("environment_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("Ports")
                        .HasColumnType("jsonb")
                        .HasColumnName("ports");

                    b.Property<int>("Replicas")
                        .HasColumnType("integer")
                        .HasColumnName("replicas");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("size");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_application");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_application_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "GIN");

                    b.HasIndex("AccountId", "AclId")
                        .HasDatabaseName("ix_application_account_id_acl_id");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_application_account_id_created_by_id");

                    b.HasIndex("AccountId", "EnvironmentId")
                        .HasDatabaseName("ix_application_account_id_environment_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_application_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_application_account_id_name");

                    b.HasIndex("AccountId", "TemplateId")
                        .HasDatabaseName("ix_application_account_id_template_id");

                    b.ToTable("application", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationDeployment", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<byte[]>("DeploymentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("deployment_hash");

                    b.Property<string>("DeploymentStatus")
                        .HasColumnType("jsonb")
                        .HasColumnName("deployment_status");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("execution_status");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<long?>("OwnerAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_account_id");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<int>("ProvisionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("provision_status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("AccountId", "ApplicationId", "Name")
                        .HasName("pk_application_deployment");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_application_deployment_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_application_deployment_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_application_deployment_account_id_name");

                    b.HasIndex("OwnerAccountId", "OwnerId")
                        .HasDatabaseName("ix_application_deployment_owner_account_id_owner_id");

                    b.ToTable("application_deployment", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationEvent", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deployment_name");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("environment_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasIndex("AccountId", "ApplicationId", "Target")
                        .HasDatabaseName("ix_application_event_account_id_application_id_target");

                    b.HasIndex("AccountId", "EnvironmentId", "Target")
                        .HasDatabaseName("ix_application_event_account_id_environment_id_target");

                    b.ToTable("application_event", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationExtension", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<long?>("EnvironmentAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("environment_account_id");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<long?>("TemplateAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_account_id");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("AccountId", "ApplicationId", "Name")
                        .HasName("pk_application_extension");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_application_extension_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_application_extension_account_id_modified_by_id");

                    b.HasIndex("EnvironmentAccountId", "EnvironmentId")
                        .HasDatabaseName("ix_application_extension_environment_account_id_environment_id");

                    b.HasIndex("TemplateAccountId", "TemplateId")
                        .HasDatabaseName("ix_application_extension_template_account_id_template_id");

                    b.ToTable("application_extension", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationSchedule", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("HttpRequest")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("http_request");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.HasKey("AccountId", "ApplicationId", "Name")
                        .HasName("pk_application_schedule");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_application_schedule_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_application_schedule_account_id_modified_by_id");

                    b.ToTable("application_schedule", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationTrace", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("environment_id");

                    b.Property<string>("Host")
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long?>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_error");

                    b.Property<string>("Method")
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<long>("RequestBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("request_bytes");

                    b.Property<long>("ResponseBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("response_bytes");

                    b.Property<string>("Service")
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasIndex("AccountId", "ApplicationId", "Service")
                        .HasDatabaseName("ix_application_trace_account_id_application_id_service");

                    b.HasIndex("AccountId", "EnvironmentId", "Service")
                        .HasDatabaseName("ix_application_trace_account_id_environment_id_service");

                    b.ToTable("application_trace", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("text")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasColumnType("text")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasColumnType("text")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_application1");

                    b.ToTable("application", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_authorization");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_authorization_application_id");

                    b.ToTable("authorization", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("role", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claim");

                    b.ToTable("role_claim", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id")
                        .HasName("pk_scope");

                    b.ToTable("scope", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_token_application_id");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("ix_token_authorization_id");

                    b.ToTable("token", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("username_index");

                    b.ToTable("user", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claim_user_id");

                    b.ToTable("user_claim", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_login");

                    b.ToTable("user_login", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserPasskey", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CredentialId")
                        .HasName("pk_user_passkey");

                    b.ToTable("user_passkey", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_token");

                    b.ToTable("user_token", "auth");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Environment", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("AclAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("acl_account_id");

                    b.Property<long>("AclId")
                        .HasColumnType("bigint")
                        .HasColumnName("acl_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encryption_key");

                    b.Property<string>("Health")
                        .HasColumnType("jsonb")
                        .HasColumnName("health");

                    b.PrimitiveCollection<string[]>("Host")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("text[]")
                        .HasColumnName("host");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("ProvisionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("provision_status");

                    b.Property<byte[]>("SshPublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ssh_public_key");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_environment");

                    b.HasIndex("SshPublicKey")
                        .HasDatabaseName("ix_environment_ssh_public_key");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_environment_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "GIN");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_environment_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_environment_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_environment_account_id_name");

                    b.HasIndex("AclAccountId", "AclId")
                        .HasDatabaseName("ix_environment_acl_account_id_acl_id");

                    b.ToTable("environment", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Identity", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("AclId")
                        .HasColumnType("bigint")
                        .HasColumnName("acl_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LockAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_after");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_identity");

                    b.HasIndex("AccountId", "AclId")
                        .HasDatabaseName("ix_identity_account_id_acl_id");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_identity_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_identity_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_account_id_name");

                    b.ToTable("identity", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.IdentityMemberOf", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.HasKey("AccountId", "IdentityId", "GroupId")
                        .HasName("pk_identity_member");

                    b.HasIndex("AccountId", "GroupId")
                        .HasDatabaseName("ix_identity_member_account_id_group_id");

                    b.ToTable("identity_member", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Llm", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AclId")
                        .HasColumnType("bigint")
                        .HasColumnName("acl_id");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("destination");

                    b.Property<string>("Fallback")
                        .HasColumnType("jsonb")
                        .HasColumnName("fallback");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.PrimitiveCollection<string[]>("Names")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("names");

                    b.Property<byte>("Routing")
                        .HasColumnType("smallint")
                        .HasColumnName("routing");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_llm");

                    b.HasIndex("AccountId", "AclId")
                        .HasDatabaseName("ix_llm_account_id_acl_id");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_llm_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_llm_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Names")
                        .IsUnique()
                        .HasDatabaseName("ix_llm_account_id_names");

                    b.ToTable("llm", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Metric", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<long>("MetricId")
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("AccountId", "Hash")
                        .HasName("pk_metric");

                    b.ToTable("metric", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.MetricValue", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("MetricId")
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasIndex("AccountId", "MetricId")
                        .HasDatabaseName("ix_metric_value_account_id_metric_id");

                    b.ToTable("metric_value", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Template", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComputedColumnSql("(definition ->> 'description')", true);

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<string>("Icon")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("icon")
                        .HasComputedColumnSql("(definition ->> 'icon')", true);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("ModifiedById")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComputedColumnSql("(definition ->> 'name')", true);

                    b.Property<string>("Target")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("target")
                        .HasComputedColumnSql("(definition ->> 'target')", true);

                    b.Property<string>("Title")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComputedColumnSql("(definition ->> 'title')", true);

                    b.Property<string>("Type")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasComputedColumnSql("(definition ->> 'type')", true);

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_template");

                    b.HasIndex("AccountId", "CategoryId")
                        .HasDatabaseName("ix_template_account_id_category_id");

                    b.HasIndex("AccountId", "CreatedById")
                        .HasDatabaseName("ix_template_account_id_created_by_id");

                    b.HasIndex("AccountId", "ModifiedById")
                        .HasDatabaseName("ix_template_account_id_modified_by_id");

                    b.HasIndex("AccountId", "Name", "Target")
                        .IsUnique()
                        .HasDatabaseName("ix_template_account_id_name_target");

                    b.ToTable("template", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.TemplateCategory", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)")
                        .HasColumnName("title");

                    b.Property<string>("Translation")
                        .HasColumnType("jsonb")
                        .HasColumnName("translation");

                    b.HasKey("AccountId", "Id")
                        .HasName("pk_template_category");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_template_category_account_id_name");

                    b.ToTable("template_category", "cs");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Acl", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acl_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.AclMember", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acl_member_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Acl", "Acl")
                        .WithMany("Members")
                        .HasForeignKey("AccountId", "AclId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acl_member_acl_account_id_acl_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("AccountId", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acl_member_identity_account_id_identity_id");

                    b.Navigation("Account");

                    b.Navigation("Acl");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApiKey", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("AccountId", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_identity_account_id_identity_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_identity_account_id_modified_by_id");

                    b.Navigation("Account");

                    b.Navigation("CreatedBy");

                    b.Navigation("Identity");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Application", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Acl", "Acl")
                        .WithMany()
                        .HasForeignKey("AccountId", "AclId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_acl_account_id_acl_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("AccountId", "EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_environment_account_id_environment_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_identity_account_id_modified_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Template", "Template")
                        .WithMany()
                        .HasForeignKey("AccountId", "TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_template_account_id_template_id");

                    b.Navigation("Account");

                    b.Navigation("Acl");

                    b.Navigation("CreatedBy");

                    b.Navigation("Environment");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationDeployment", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_deployment_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Application", "Application")
                        .WithMany("Deployments")
                        .HasForeignKey("AccountId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_deployment_application_account_id_application_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_deployment_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_deployment_identity_account_id_modified_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId", "OwnerId")
                        .HasConstraintName("fk_application_deployment_identity_owner_account_id_owner_id");

                    b.Navigation("Account");

                    b.Navigation("Application");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationExtension", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_extension_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Application", "Application")
                        .WithMany("Extensions")
                        .HasForeignKey("AccountId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_extension_application_account_id_application_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_extension_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_extension_identity_account_id_modified_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentAccountId", "EnvironmentId")
                        .HasConstraintName("fk_application_extension_environment_environment_account_id_en");

                    b.HasOne("ChurrOS.Api.Domain.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateAccountId", "TemplateId")
                        .HasConstraintName("fk_application_extension_template_template_account_id_template");

                    b.Navigation("Account");

                    b.Navigation("Application");

                    b.Navigation("CreatedBy");

                    b.Navigation("Environment");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.ApplicationSchedule", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_schedule_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Application", "Application")
                        .WithMany()
                        .HasForeignKey("AccountId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_schedule_application_account_id_application_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_schedule_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_schedule_identity_account_id_modified_by_id");

                    b.Navigation("Account");

                    b.Navigation("Application");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdAuthorization", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Auth.OpenIdApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_authorization_application_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdToken", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Auth.OpenIdApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_token_application_application_id");

                    b.HasOne("ChurrOS.Api.Domain.Auth.OpenIdAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_token_authorization_authorization_id");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserClaim", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Auth.OpenIdUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claim_users_user_id");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserPasskey", b =>
                {
                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("OpenIdUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("OpenIdUserPasskeyCredentialId");

                            b1.ToTable("user_passkey", "auth");

                            b1.ToJson("data");

                            b1.WithOwner()
                                .HasForeignKey("OpenIdUserPasskeyCredentialId")
                                .HasConstraintName("fk_user_passkeys_user_passkeys_credential_id");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdUserRole", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Auth.OpenIdRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Environment", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_environment_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_environment_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_environment_identity_account_id_modified_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Acl", "Acl")
                        .WithMany()
                        .HasForeignKey("AclAccountId", "AclId")
                        .HasConstraintName("fk_environment_acl_acl_account_id_acl_id");

                    b.Navigation("Account");

                    b.Navigation("Acl");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Identity", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Acl", "Acl")
                        .WithMany()
                        .HasForeignKey("AccountId", "AclId")
                        .HasConstraintName("fk_identity_acl_account_id_acl_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .HasConstraintName("fk_identity_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .HasConstraintName("fk_identity_identity_account_id_modified_by_id");

                    b.Navigation("Account");

                    b.Navigation("Acl");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.IdentityMemberOf", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_member_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "Group")
                        .WithMany()
                        .HasForeignKey("AccountId", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_member_identity_account_id_group_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "Identity")
                        .WithMany("MemberOf")
                        .HasForeignKey("AccountId", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_member_identity_account_id_identity_id");

                    b.Navigation("Account");

                    b.Navigation("Group");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Llm", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_llm_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.Acl", "Acl")
                        .WithMany()
                        .HasForeignKey("AccountId", "AclId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_llm_acl_account_id_acl_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_llm_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_llm_identity_account_id_modified_by_id");

                    b.Navigation("Account");

                    b.Navigation("Acl");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Metric", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metric_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Template", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_account_account_id");

                    b.HasOne("ChurrOS.Api.Domain.TemplateCategory", "Category")
                        .WithMany("Templates")
                        .HasForeignKey("AccountId", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_template_category_account_id_category_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_identity_account_id_created_by_id");

                    b.HasOne("ChurrOS.Api.Domain.Identity", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("AccountId", "ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_identity_account_id_modified_by_id");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.TemplateCategory", b =>
                {
                    b.HasOne("ChurrOS.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_category_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Acl", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Application", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Extensions");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Auth.OpenIdAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.Identity", b =>
                {
                    b.Navigation("MemberOf");
                });

            modelBuilder.Entity("ChurrOS.Api.Domain.TemplateCategory", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
