[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:console]
command=/app/console.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:file-browser]
command=/app/file-browser.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:terminal]
command=/app/terminal.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true